
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ibrahimildiran
 */
public class PersonelLoginEkran extends javax.swing.JFrame {

    /**
     * Creates new form PersonelLoginEkran
     */
   

    public PersonelLoginEkran() {
        setResizable(false);
        this.setTitle("Personel Giriş Ekranı");
        
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_geriDon = new javax.swing.JButton();
        btn_giris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 0, 102));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        txt_kullaniciAdi.setBackground(new java.awt.Color(153, 153, 153));
        txt_kullaniciAdi.setMaximumSize(new java.awt.Dimension(180, 35));
        txt_kullaniciAdi.setMinimumSize(new java.awt.Dimension(180, 35));
        txt_kullaniciAdi.setPreferredSize(new java.awt.Dimension(180, 35));
        txt_kullaniciAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kullaniciAdiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KULLANICI ADI : ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ŞİFRE : ");

        txt_sifre.setBackground(new java.awt.Color(153, 153, 153));
        txt_sifre.setMaximumSize(new java.awt.Dimension(180, 35));
        txt_sifre.setMinimumSize(new java.awt.Dimension(180, 35));
        txt_sifre.setPreferredSize(new java.awt.Dimension(180, 35));
        txt_sifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_sifreActionPerformed(evt);
            }
        });

        jCheckBox1.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Robot Değilim.");

        btn_geriDon.setBackground(new java.awt.Color(153, 153, 153));
        btn_geriDon.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_geriDon.setText("GERİ DÖN");
        btn_geriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriDonActionPerformed(evt);
            }
        });

        btn_giris.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_giris.setText("GİRİŞ");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(88, 88, 88)
                            .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(155, 155, 155))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_kullaniciAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kullaniciAdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kullaniciAdiActionPerformed

    private void btn_geriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriDonActionPerformed
        // TODO add your handling code here:
        giris giris2 = new giris();
        giris2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_geriDonActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
// TODO add your handling code here:

        String Username = "";
        String Password = "";
        //İlk başta textfield'ların dolu olup olmadığını kontrol ediyorum.
        if (txt_kullaniciAdi.getText().isEmpty() || txt_kullaniciAdi.getText().equals("Kullanıcı Adınızı Giriniz")) {
            JOptionPane.showMessageDialog(null, "Lütfen kullanıcı adınızı giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Username = txt_kullaniciAdi.getText();
            String pattern = "(?=\\S+$).{1,}";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(Username);

            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Kullanici adinda bosluk bulunamaz!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        //Verdiğim pattern örneği ile şifrenin kurallara uygun girilip girilmediğini kontrol ediyorum.
        if (txt_sifre.getText().isEmpty() || txt_sifre.getText().equals("jPasswordField1")) {
            JOptionPane.showMessageDialog(null, "Şifreniz yanlış! Lütfen şifrenizi doğrunuzu giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Password = txt_sifre.getText();
        }
        System.out.println(Login_Info());
        int count = 0;
        Boolean isExist = false;
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1", "app", "app");
            Statement s = con.createStatement();
            String query = "SELECT * FROM PERSONEL ";
            ResultSet rs = s.executeQuery(query);
            while (rs.next()) {
                String UsernameDB = rs.getString("USERNAME");
                String PasswordDB = rs.getString("PASSWORD");
                if (Username.equals(UsernameDB) && Password.equals(PasswordDB) && jCheckBox1.isSelected()) {
                    
                    isExist = true;
                    this.dispose();
                    personelAnaEkran giris3 = new personelAnaEkran(Username, Password);
                    giris3.setVisible(true);
                    Graphic g = new Graphic("Personel Ekranına Hoşgeldiniz");
                    g.setLocation(600, 600);
                    g.setVisible(true);
                    g.setLocationRelativeTo(this);
                    break;

                }

            }
            if (!jCheckBox1.isSelected()) {
                JOptionPane.showMessageDialog(null, "Lutfen kutucugu isaretleyiniz.");
                return;
            } else if (!isExist) {
                JOptionPane.showMessageDialog(null, "Girilen bilgilere ait kullanici bulunamadi.");
                return;
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
        this.dispose();
    }//GEN-LAST:event_btn_girisActionPerformed

    private void txt_sifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_sifreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_sifreActionPerformed

    public String Login_Info() {
        return txt_kullaniciAdi.getText();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelLoginEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geriDon;
    private javax.swing.JButton btn_giris;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JTextField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
