
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author ibrahimildiran
 */
public class personelAnaEkran extends javax.swing.JFrame {

    /**
     * Creates new form personelAnaEkran
     *
     */
    static String Username;
    static String Password;

    public personelAnaEkran(String Username, String Password) {
        this.Username = Username;
        this.Password = Password;
        setResizable(false);
        this.setTitle("Personel Ana Ekran");
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_personelAnaEkran = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        btn_personelAnaEkranGeriDon = new javax.swing.JButton();
        pnl_izinIste = new javax.swing.JPanel();
        lbl_personelAnaEkranIzinIste = new javax.swing.JLabel();
        lbl_personelAnaEkranIzinSebebi = new javax.swing.JLabel();
        jComboBox_PersonelAnaEkranIzinSebebi = new javax.swing.JComboBox<>();
        btn_personelanaEkranIzinIste = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        pnl_zamIste = new javax.swing.JPanel();
        lbl_personelAnaEkranZamIste = new javax.swing.JLabel();
        txt_personelAnaEkranZamIste = new javax.swing.JTextField();
        lbl_personelAnaEkranZamSebebi = new javax.swing.JLabel();
        jComboBox_personelAnaEkranZamNedeni = new javax.swing.JComboBox<>();
        btn_personelAnaEkranZamIste = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_personelAnaEkraniGoruntule = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_personelDurumZam = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        btn_personelAnaEkranGeriDon.setText("GERİ DÖN");
        btn_personelAnaEkranGeriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelAnaEkranGeriDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(709, Short.MAX_VALUE)
                .addComponent(btn_personelAnaEkranGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(385, Short.MAX_VALUE)
                .addComponent(btn_personelAnaEkranGeriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jTabbedPane_personelAnaEkran.addTab("Ana Ekran", jPanel2);

        pnl_izinIste.setBackground(new java.awt.Color(102, 102, 102));

        lbl_personelAnaEkranIzinIste.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lbl_personelAnaEkranIzinIste.setForeground(new java.awt.Color(255, 255, 255));
        lbl_personelAnaEkranIzinIste.setText("İZİN İSTENEN GÜN SAYISI : ");

        lbl_personelAnaEkranIzinSebebi.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lbl_personelAnaEkranIzinSebebi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_personelAnaEkranIzinSebebi.setText("İZİN SEBEBİ : ");

        jComboBox_PersonelAnaEkranIzinSebebi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ailevi Durumlar", "Sağlıksal Durumlar", "Dinlenmek ", "Seyahat İçin", "Randevum Var", "Diğer", " " }));

        btn_personelanaEkranIzinIste.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_personelanaEkranIzinIste.setText("İZİN İSTE");
        btn_personelanaEkranIzinIste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelanaEkranIzinIsteActionPerformed(evt);
            }
        });

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        javax.swing.GroupLayout pnl_izinIsteLayout = new javax.swing.GroupLayout(pnl_izinIste);
        pnl_izinIste.setLayout(pnl_izinIsteLayout);
        pnl_izinIsteLayout.setHorizontalGroup(
            pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izinIsteLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_personelAnaEkranIzinIste)
                    .addComponent(lbl_personelAnaEkranIzinSebebi, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_personelanaEkranIzinIste, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_PersonelAnaEkranIzinSebebi, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(336, Short.MAX_VALUE))
        );
        pnl_izinIsteLayout.setVerticalGroup(
            pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_izinIsteLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_personelAnaEkranIzinIste, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_izinIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_PersonelAnaEkranIzinSebebi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_personelAnaEkranIzinSebebi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_personelanaEkranIzinIste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );

        jTabbedPane_personelAnaEkran.addTab("İzin İste", pnl_izinIste);

        pnl_zamIste.setBackground(new java.awt.Color(102, 102, 102));

        lbl_personelAnaEkranZamIste.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lbl_personelAnaEkranZamIste.setForeground(new java.awt.Color(255, 255, 255));
        lbl_personelAnaEkranZamIste.setText("ZAM İSTENEN TUTAR : ");

        txt_personelAnaEkranZamIste.setBackground(new java.awt.Color(153, 153, 153));
        txt_personelAnaEkranZamIste.setMaximumSize(new java.awt.Dimension(180, 35));
        txt_personelAnaEkranZamIste.setMinimumSize(new java.awt.Dimension(180, 35));
        txt_personelAnaEkranZamIste.setPreferredSize(new java.awt.Dimension(180, 35));

        lbl_personelAnaEkranZamSebebi.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lbl_personelAnaEkranZamSebebi.setForeground(new java.awt.Color(255, 255, 255));
        lbl_personelAnaEkranZamSebebi.setText("ZAM İSTEME NEDENİ : ");

        jComboBox_personelAnaEkranZamNedeni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cocuklar aç", "karı gratise gidecek", " " }));

        btn_personelAnaEkranZamIste.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_personelAnaEkranZamIste.setText("ZAM İSTE");
        btn_personelAnaEkranZamIste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelAnaEkranZamIsteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_zamIsteLayout = new javax.swing.GroupLayout(pnl_zamIste);
        pnl_zamIste.setLayout(pnl_zamIsteLayout);
        pnl_zamIsteLayout.setHorizontalGroup(
            pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_zamIsteLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addGroup(pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_personelAnaEkranZamIste, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_zamIsteLayout.createSequentialGroup()
                        .addGroup(pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_personelAnaEkranZamSebebi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_personelAnaEkranZamIste, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_personelAnaEkranZamIste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox_personelAnaEkranZamNedeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        pnl_zamIsteLayout.setVerticalGroup(
            pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_zamIsteLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_personelAnaEkranZamIste, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_personelAnaEkranZamIste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnl_zamIsteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl_personelAnaEkranZamSebebi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox_personelAnaEkranZamNedeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_personelAnaEkranZamIste, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane_personelAnaEkran.addTab("Zam İste", pnl_zamIste);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PERSONEL_ID", "GUN_SAYISI", "SEBEP", "DURUM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Connection con;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1","app","app");
            Statement s = con.createStatement();
            String query = "SELECT * FROM IZIN2";
            ResultSet rs = s.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            while(rs.next()){
                int Gun = rs.getInt("GUN");
                String Sebep = rs.getString("SEBEP");
                int Personel_ID = rs.getInt("PERSONEL_ID");
                String Onay = rs.getString("ONAY");
                String [] row = {Integer.toString(Gun),Sebep,Integer.toString(Personel_ID),Onay};
                model.addRow(row);
            }

        }catch(SQLException e){
            e.printStackTrace();
        }
        jScrollPane1.setViewportView(jTable1);

        btn_personelAnaEkraniGoruntule.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_personelAnaEkraniGoruntule.setText("GÖRÜNTÜLE");
        btn_personelAnaEkraniGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_personelAnaEkraniGoruntuleActionPerformed(evt);
            }
        });

        tbl_personelDurumZam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PERSONEL_ID", "MIKTAR", "SEBEP", "DURUM"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1","app","app");
            Statement s = con.createStatement();
            String query = "SELECT * FROM ZAM";
            ResultSet rs = s.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel)tbl_personelDurumZam.getModel();
            while(rs.next()){
                int Personel_ID = rs.getInt("PERSONEL_ID");
                int Miktar = rs.getInt("MIKTAR");
                String Sebep = rs.getString("SEBEP");
                String Onay = rs.getString("ONAY");
                String [] row = {Integer.toString(Personel_ID),Integer.toString(Miktar),Sebep,Onay};
                model.addRow(row);
            }

        }catch(SQLException e){
            e.printStackTrace();
        }
        jScrollPane3.setViewportView(tbl_personelDurumZam);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(btn_personelAnaEkraniGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addComponent(btn_personelAnaEkraniGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jTabbedPane_personelAnaEkran.addTab("Durumum", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_personelAnaEkran)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane_personelAnaEkran)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //personelin izin istemesini gerçekleştirir
    //başlangıçta izinGun 0 atanır daha sonra jSpinnerdan bir sayı alınır eğer sayı
    // 0 ise uyarı mesajı verir 0 gün izin istenmeyeceği için. jspinnerdan alınan değer 0 değil ise
    //izinGune jspinnerdan alınan değer atanır.
    private void btn_personelanaEkranIzinIsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelanaEkranIzinIsteActionPerformed
        // TODO add your handling code here:
        int izinGun = 0;
        if ((Integer) jSpinner1.getValue() == 0) {
            JOptionPane.showMessageDialog(null, "Lütfen izin istediginiz gun sayisini giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            izinGun = (Integer) jSpinner1.getValue();
        }
        //comboboxtaki sebeplerden bir tanesi alınır sebep değişkenine atanıyor.
        String sebep = jComboBox_PersonelAnaEkranIzinSebebi.getSelectedItem().toString();
        PersonelLoginEkran p1 = new PersonelLoginEkran();
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1", "app", "app");
            Statement s = con.createStatement();
            //veritabından PERSONEL tablosundaki ID sütunundan USERNAME sütunu Username değişkenine eşit olan
            //satırın ID değerini döndürüyor
            String queryGet = "SELECT ID  as PERSON_ID FROM PERSONEL WHERE USERNAME = '" + Username + "'";
            ResultSet rs = s.executeQuery(queryGet);
            rs.next();
            int count = rs.getInt("PERSON_ID");
            rs.close();
            System.out.println(count);
            //sorgu IZIN2 tablosuna GUN SEBEP PERSONEL_ID VE ONAY sutunlarına veri eklemek için kullanılıyor
            // izinGun sebep count değişkeni ve false değeri atanır sorgu çalıştırılır onay sutununa ilk değer 
            // false verdim onaylanmamış olduğunu gormek için.
            String query = "INSERT INTO IZIN2 (GUN,SEBEP,PERSONEL_ID,ONAY) VALUES(?,?,?,?) ";
            PreparedStatement pst = con.prepareCall(query);
            pst.setInt(1, izinGun);
            pst.setString(2, sebep);
            pst.setInt(3, count);
            pst.setBoolean(4, false);
            pst.executeUpdate();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_personelanaEkranIzinIsteActionPerformed
    // zam iste metodudur baslangıçta zam miktarını ve boş string aldım kontrol etmek için 
    // sonuçta boş istek yollamaması gerekir.eğer boş değilse comboboxtan alınan veriyle 
    // textField dan alınan veriyi alır.
    private void btn_personelAnaEkranZamIsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelAnaEkranZamIsteActionPerformed
        // TODO add your handling code here:
   
        String ZamMiktar = "";
        String ZamSebep = jComboBox_personelAnaEkranZamNedeni.getSelectedItem().toString();
        if (txt_personelAnaEkranZamIste.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lütfen  istediginiz zam miktarini giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            ZamMiktar = txt_personelAnaEkranZamIste.getText();
        }
        PersonelLoginEkran p1 = new PersonelLoginEkran();
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1", "app", "app");
            Statement s = con.createStatement();
            //veritabından PERSONEL tablosundaki ID sütunundan USERNAME sütunu Username değişkenine eşit olan
            //satırın ID değerini döndürüyor
            String queryGet = "SELECT ID  as PERSON_ID FROM PERSONEL WHERE USERNAME = '" + Username + "'";
            ResultSet rs = s.executeQuery(queryGet);
            rs.next();
            int count = rs.getInt("PERSON_ID");
            rs.close();
            System.out.println(count);
             //sorgu ZAM tablosuna MIKTAR SEBEP PERSONEL_ID VE ONAY sutunlarına veri eklemek için kullanılıyor
            // izinGun sebep count değişkeni ve false değeri atanır sorgu çalıştırılır onay sutununa ilk değer 
            // false verdim onaylanmamış olduğunu gormek için.
            String query = "INSERT INTO ZAM (MIKTAR,SEBEP,PERSONEL_ID,ONAY) VALUES(?,?,?,?) ";
            PreparedStatement pst = con.prepareCall(query);
            pst.setInt(1, Integer.parseInt(ZamMiktar));
            pst.setString(2, ZamSebep);
            pst.setInt(3, count);
            pst.setBoolean(4, false);
            pst.executeUpdate();
            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_personelAnaEkranZamIsteActionPerformed

    private void btn_personelAnaEkraniGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_personelAnaEkraniGoruntuleActionPerformed
        // TODO add your handling code here:
        Connection con;
        try {
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1", "app", "app");
            Statement s = con.createStatement();

            String queryCount = "SELECT COUNT(ID) as IDcount FROM IZIN2";
            ResultSet rsCount = s.executeQuery(queryCount);
            rsCount.next();
            int Count = rsCount.getInt("IDcount");
            rsCount.close();

            String query = "SELECT * FROM IZIN2";
            ResultSet rs = s.executeQuery(query);
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            int i = 0;
            while (rs.next()) {
                int Gun = rs.getInt("GUN");
                model.setValueAt(Gun, i, 0);
                String Sebep = rs.getString("SEBEP");
                model.setValueAt(Sebep, i, 1);
                int Personel_ID = rs.getInt("PERSONEL_ID");
                model.setValueAt(Personel_ID, i, 2);
                String Onay = rs.getString("ONAY");
                model.setValueAt(Onay, i, 3);
                String[] row = {Integer.toString(Gun), Sebep, Integer.toString(Personel_ID), Onay};
                Update_Table(row, Count);
                i++;
            }
            rs.close();

            String queryZamCount = "SELECT COUNT(ID) as IDcount FROM ZAM";
            ResultSet rsZamCount = s.executeQuery(queryZamCount);
            rsZamCount.next();
            int ZamCount = rsZamCount.getInt("IDcount");
            rsZamCount.close();

            String queryZam = "SELECT * FROM ZAM";
            ResultSet rsZam = s.executeQuery(queryZam);
            DefaultTableModel modelZam = (DefaultTableModel) tbl_personelDurumZam.getModel();
            int i2 = 0;
            while (rsZam.next()) {
                int Personel_ID = rsZam.getInt("PERSONEL_ID");
                modelZam.setValueAt(Personel_ID, i2, 0);
                int Miktar = rsZam.getInt("MIKTAR");
                modelZam.setValueAt(Miktar, i2, 1);
                String Sebep = rsZam.getString("SEBEP");
                modelZam.setValueAt(Sebep, i2, 2);
                String Onay = rsZam.getString("ONAY");
                modelZam.setValueAt(Onay, i2, 3);
                String[] row = {Integer.toString(Personel_ID), Integer.toString(Miktar), Sebep, Onay};
                Update_Table2(row, ZamCount);
                i2++;
            }
            rsZam.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_personelAnaEkraniGoruntuleActionPerformed

    private void btn_personelAnaEkranGeriDonActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog(null, "giriş ekranına dönmek istediğinize emin misiniz?", "WARNING", JOptionPane.YES_NO_OPTION);
        if (dialogButton == JOptionPane.YES_OPTION) {
            giris giris1 = new giris();
            giris1.setVisible(true);
            this.dispose();
        } else {
            remove(dialogButton);
        }

    }                                            

    public void Update_Table(String[] row, int count) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(count - 1);
        model.addRow(row);
    }

    public void Update_Table2(String[] row, int count) {
        DefaultTableModel modelZam = (DefaultTableModel) tbl_personelDurumZam.getModel();
        modelZam.setRowCount(count - 1);
        modelZam.addRow(row);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(personelAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(personelAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(personelAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(personelAnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new personelAnaEkran(Username, Password).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_personelAnaEkranGeriDon;
    private javax.swing.JButton btn_personelAnaEkranZamIste;
    private javax.swing.JButton btn_personelAnaEkraniGoruntule;
    private javax.swing.JButton btn_personelanaEkranIzinIste;
    private javax.swing.JComboBox<String> jComboBox_PersonelAnaEkranIzinSebebi;
    private javax.swing.JComboBox<String> jComboBox_personelAnaEkranZamNedeni;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane_personelAnaEkran;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_personelAnaEkranIzinIste;
    private javax.swing.JLabel lbl_personelAnaEkranIzinSebebi;
    private javax.swing.JLabel lbl_personelAnaEkranZamIste;
    private javax.swing.JLabel lbl_personelAnaEkranZamSebebi;
    private javax.swing.JPanel pnl_izinIste;
    private javax.swing.JPanel pnl_zamIste;
    private javax.swing.JTable tbl_personelDurumZam;
    private javax.swing.JTextField txt_personelAnaEkranZamIste;
    // End of variables declaration//GEN-END:variables
}
