
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ibrahimildiran
 */
public class yoneticiLoginEkran extends javax.swing.JFrame {

    /**
     * Creates new form yoneticiAnaEkran
     */
    public yoneticiLoginEkran() {
        setResizable(false);
        this.setTitle("Yönetici Giriş Ekranı");
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_kullaniciAdi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_sifre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_geriDon = new javax.swing.JButton();
        btn_giris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));

        txt_kullaniciAdi.setBackground(new java.awt.Color(153, 153, 153));
        txt_kullaniciAdi.setMaximumSize(new java.awt.Dimension(180, 35));
        txt_kullaniciAdi.setMinimumSize(new java.awt.Dimension(180, 35));
        txt_kullaniciAdi.setPreferredSize(new java.awt.Dimension(180, 35));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KULLANICI ADI : ");

        txt_sifre.setBackground(new java.awt.Color(153, 153, 153));
        txt_sifre.setMaximumSize(new java.awt.Dimension(180, 35));
        txt_sifre.setMinimumSize(new java.awt.Dimension(180, 35));
        txt_sifre.setPreferredSize(new java.awt.Dimension(180, 35));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ŞİFRE : ");

        btn_geriDon.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_geriDon.setText("GERİ DÖN");
        btn_geriDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_geriDonActionPerformed(evt);
            }
        });

        btn_giris.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        btn_giris.setText("GİRİŞ");
        btn_giris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_girisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)
                                .addComponent(txt_sifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txt_kullaniciAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_sifre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_giris, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_geriDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(156, 156, 156))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_geriDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_geriDonActionPerformed
        // TODO add your handling code here:
        giris giris2= new giris();
        giris2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_geriDonActionPerformed

    private void btn_girisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_girisActionPerformed
       // TODO add your handling code here:
        String Username = "";
        String Password = "";
        if (txt_kullaniciAdi.getText().isEmpty() || txt_kullaniciAdi.getText().equals("Kullanıcı Adınızı Giriniz")) {
            JOptionPane.showMessageDialog(null, "Lütfen kullanıcı adınızı giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Username = txt_kullaniciAdi.getText();
                         String pattern = "(?=\\S+$).{1,}";
            Pattern p = Pattern.compile(pattern);
            Matcher m = p.matcher(Username);

            if (!m.matches()) {
                JOptionPane.showMessageDialog(null, "Kullanici adinda bosluk bulunamaz!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        //Verdiğim pattern örneği ile şifrenin kurallara uygun girilip girilmediğini kontrol ediyorum.
        if (txt_sifre.getText().isEmpty() || txt_sifre.getText().equals("jPasswordField1")) {
            JOptionPane.showMessageDialog(null, "Şifreniz yanlış! Lütfen şifrenizi doğrunuzu giriniz.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            Password = txt_sifre.getText();
        }
        int count = 0;
        Connection con;
        Boolean isExist = false;
        try{
            con = DriverManager.getConnection("jdbc:derby://localhost:1527/db1","app","app");
            Statement s = con.createStatement();
            String query = "SELECT * FROM MANAGER ";
            ResultSet rs = s.executeQuery(query);
            System.out.println(rs);
            while(rs.next()){
                String UsernameDB = rs.getString("USERNAME");
                String PasswordDB = rs.getString("PASSWORD");
                if(Username.equals(UsernameDB)&& Password.equals(PasswordDB)){
                    yoneticiAnaEkran giris3= new yoneticiAnaEkran();
                    isExist= true;
                    this.dispose();
                    giris3.setVisible(true);
                    Graphic g = new Graphic("Yönetici Ekranına Hoşgeldiniz");
                    g.setLocation(350, 235);
                    g.setVisible(true);
                    g.setLocationRelativeTo(this);
                    break;
                    
                }
            }
            if(!isExist){
                    JOptionPane.showMessageDialog(null, "Girilen bilgilere ait kullanici bulunamadi.");
                    return;
                }
        }catch(SQLException e){
            e.printStackTrace();
        }


        this.dispose();
    }//GEN-LAST:event_btn_girisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yoneticiLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yoneticiLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yoneticiLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yoneticiLoginEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yoneticiLoginEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_geriDon;
    private javax.swing.JButton btn_giris;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_kullaniciAdi;
    private javax.swing.JTextField txt_sifre;
    // End of variables declaration//GEN-END:variables
}
